//#######################################################################
//File generated by BMP2C V1.18 17.01.2008
//hk@holger-klabunde.de
//http://www.holger-klabunde.de
//6 pixel per byte for T6963 and 6x8 font
//Horizontal pixel orientation for T6963
//Pixel orientation per Byte: D7..D0 
//#######################################################################
#ifndef GLCD_Clock_h //don't do multiple includes of this file
#define GLCD_Clock_h

#include <avr/pgmspace.h> //Win-AVR
//#include <progmem.h> //AVR-GCC

#define GLCD_ClockWIDTH 	64	//Width in pixels
#define GLCD_ClockHEIGHT 	64	//Height in pixels
#define GLCD_ClockBYTEWIDTH 	11	//Width in bytes

//extern const rom unsigned char GLCD_Clockbmp[]; //Microchip C18
//extern const unsigned char code GLCD_Clockbmp[]; //Keil
//extern const unsigned char GLCD_Clockbmp[]; //SDCC

extern prog_uchar GLCD_Clockbmp[]; //AVR-GCC, WinAVR

#endif //GLCD_Clock_h
